-- VHDL Entity alien_game_lib.c1_t3_interactive_LED.symbol
--
-- Created:
--          by - phanq.UNKNOWN (HTC219-722-SPC)
--          at - 11:39:44 12.02.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c1_t3_interactive_LED IS
   PORT( 
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0) BUS;
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c1_t3_interactive_LED ;

--
-- VHDL Architecture alien_game_lib.c1_t3_interactive_LED.struct
--
-- Created:
--          by - phanq.UNKNOWN (HTC219-722-SPC)
--          at - 11:39:43 12.02.2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c1_t3_interactive_LED IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout0 : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout4 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout5 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout6 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout7 : std_logic_vector(7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_10' of 'split'
   SIGNAL mw_U_10temp_din : std_logic_vector(3 DOWNTO 0);


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'constval'
   dout <= "011001100000101111101101";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   dout3 <= "000100101101011010000111";

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   dout4 <= "00000001";

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   dout5 <= "01100100";

   -- ModuleWare code(v1.12) for instance 'U_4' of 'constval'
   dout6 <= "11101000";

   -- ModuleWare code(v1.12) for instance 'U_5' of 'constval'
   dout7 <= "00001010";

   -- ModuleWare code(v1.12) for instance 'U_7' of 'mux'
   u_7combo_proc: PROCESS(dout, dout3, dout0)
   BEGIN
      CASE dout0 IS
      WHEN '0' => color_BGR <= dout;
      WHEN '1' => color_BGR <= dout3;
      WHEN OTHERS => color_BGR <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_7combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'mux'
   u_8combo_proc: PROCESS(dout4, dout5, dout1)
   BEGIN
      CASE dout1 IS
      WHEN '0' => x_coord <= dout4;
      WHEN '1' => x_coord <= dout5;
      WHEN OTHERS => x_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_8combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'mux'
   u_9combo_proc: PROCESS(dout6, dout7, dout2)
   BEGIN
      CASE dout2 IS
      WHEN '0' => y_coord <= dout6;
      WHEN '1' => y_coord <= dout7;
      WHEN OTHERS => y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_9combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'split'
   mw_U_10temp_din <= btn;
   u_10combo_proc: PROCESS (mw_U_10temp_din)
   VARIABLE temp_din: std_logic_vector(3 DOWNTO 0);
   BEGIN
      temp_din := mw_U_10temp_din(3 DOWNTO 0);
      dout0 <= temp_din(0);
      dout1 <= temp_din(1);
      dout2 <= temp_din(2);
   END PROCESS u_10combo_proc;

   -- Instance port mappings.

END struct;
