-- VHDL Entity alien_game_lib.c2_t7_shift_direction.symbol
--
-- Created:
--          by - USER.UNKNOWN (QUANG-PHAN)
--          at - 21:51:31 02/23/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t7_shift_direction IS
   PORT( 
      last_dir : IN     std_logic;
      x_coord  : IN     std_logic_vector (7 DOWNTO 0);
      dir      : OUT    std_logic
   );

-- Declarations

END c2_t7_shift_direction ;

--
-- VHDL Architecture alien_game_lib.c2_t7_shift_direction.struct
--
-- Created:
--          by - USER.UNKNOWN (QUANG-PHAN)
--          at - 21:51:31 02/23/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t7_shift_direction IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout   : std_logic;
   SIGNAL edge   : std_logic;
   SIGNAL l_edge : std_logic;
   SIGNAL r_edge : std_logic;



BEGIN

   -- ModuleWare code(v1.12) for instance 'l_edge' of 'and'
   l_edge <= x_coord(7) AND last_dir;

   -- ModuleWare code(v1.12) for instance 'r_edge' of 'and'
   r_edge <= x_coord(0) AND NOT(last_dir);

   -- ModuleWare code(v1.12) for instance 'U_1' of 'inv'
   dout <= NOT(last_dir);

   -- ModuleWare code(v1.12) for instance 'U_0' of 'mux'
   u_0combo_proc: PROCESS(last_dir, dout, edge)
   BEGIN
      CASE edge IS
      WHEN '0' => dir <= last_dir;
      WHEN '1' => dir <= dout;
      WHEN OTHERS => dir <= 'X';
      END CASE;
   END PROCESS u_0combo_proc;

   -- ModuleWare code(v1.12) for instance 'edge' of 'or'
   edge <= r_edge OR l_edge;

   -- Instance port mappings.

END struct;
