-- VHDL Entity alien_game_lib.c2_t2_decrementer.symbol
--
-- Created:
--          by - USER.UNKNOWN (QUANG-PHAN)
--          at - 16:03:00 02/15/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t2_decrementer IS
   PORT( 
      input  : IN     std_logic_vector (2 DOWNTO 0);
      result : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END c2_t2_decrementer ;

--
-- VHDL Architecture alien_game_lib.c2_t2_decrementer.struct
--
-- Created:
--          by - USER.UNKNOWN (QUANG-PHAN)
--          at - 16:11:51 02/15/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c2_t2_decrementer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL cout  : std_logic;
   SIGNAL cout1 : std_logic;
   SIGNAL dout  : std_logic;
   SIGNAL dout0 : std_logic;
   SIGNAL dout1 : std_logic;
   SIGNAL dout2 : std_logic;
   SIGNAL dout3 : std_logic;
   SIGNAL sum   : std_logic;
   SIGNAL sum1  : std_logic;
   SIGNAL sum2  : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_5' of 'split'
   SIGNAL mw_U_5temp_din : std_logic_vector(2 DOWNTO 0);

   -- Component Declarations
   COMPONENT c2_t2_full_adder
   PORT (
      a    : IN     std_logic ;
      b    : IN     std_logic ;
      cin  : IN     std_logic ;
      cout : OUT    std_logic ;
      sum  : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t2_full_adder USE ENTITY alien_game_lib.c2_t2_full_adder;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   dout <= '0';

   -- ModuleWare code(v1.12) for instance 'U_4' of 'constval'
   dout3 <= '1';

   -- ModuleWare code(v1.12) for instance 'U_6' of 'merge'
   result <= sum2 & sum1 & sum;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'split'
   mw_U_5temp_din <= input;
   u_5combo_proc: PROCESS (mw_U_5temp_din)
   VARIABLE temp_din: std_logic_vector(2 DOWNTO 0);
   BEGIN
      temp_din := mw_U_5temp_din(2 DOWNTO 0);
      dout0 <= temp_din(0);
      dout1 <= temp_din(1);
      dout2 <= temp_din(2);
   END PROCESS u_5combo_proc;

   -- Instance port mappings.
   U_0 : c2_t2_full_adder
      PORT MAP (
         a    => dout0,
         b    => dout3,
         cin  => dout,
         cout => cout,
         sum  => sum
      );
   U_1 : c2_t2_full_adder
      PORT MAP (
         a    => dout1,
         b    => dout3,
         cin  => cout,
         cout => cout1,
         sum  => sum1
      );
   U_2 : c2_t2_full_adder
      PORT MAP (
         a    => dout2,
         b    => dout3,
         cin  => cout1,
         cout => OPEN,
         sum  => sum2
      );

END struct;
