-- VHDL Entity alien_game_lib.c3_t3_button_debounce.symbol
--
-- Created:
--          by - USER.UNKNOWN (QUANG-PHAN)
--          at - 16:09:48 05/20/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c3_t3_button_debounce IS
   PORT( 
      btn         : IN     std_logic;
      clk         : IN     std_logic;
      rst_n       : IN     std_logic;
      btn_pressed : OUT    std_logic
   );

-- Declarations

END c3_t3_button_debounce ;

--
-- VHDL Architecture alien_game_lib.c3_t3_button_debounce.fsm
--
-- Created:
--          by - USER.UNKNOWN (QUANG-PHAN)
--          at - 16:09:48 05/20/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF c3_t3_button_debounce IS

   TYPE STATE_TYPE IS (
      init,
      pressed,
      s0
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare Wait State internal signals
   SIGNAL csm_timer : std_logic_vector(22 DOWNTO 0);
   SIGNAL csm_next_timer : std_logic_vector(22 DOWNTO 0);
   SIGNAL csm_timeout : std_logic;
   SIGNAL csm_to_s0 : std_logic;

   -- Declare any pre-registered internal signals
   SIGNAL btn_pressed_int : std_logic ;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst_n
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst_n = '0') THEN
         current_state <= init;
         csm_timer <= (OTHERS => '0');
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
         csm_timer <= csm_next_timer;
         -- Registered output assignments
         btn_pressed <= btn_pressed_int;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      btn,
      csm_timeout,
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm_to_s0 <= '0';
      CASE current_state IS
         WHEN init => 
            IF (btn = '1') THEN 
               next_state <= pressed;
            ELSIF (btn = '0') THEN 
               next_state <= init;
            ELSE
               next_state <= init;
            END IF;
         WHEN pressed => 
            next_state <= s0;
            csm_to_s0 <= '1';
         WHEN s0 => 
            IF (csm_timeout = '1') THEN 
               next_state <= init;
            ELSE
               next_state <= s0;
            END IF;
         WHEN OTHERS =>
            next_state <= init;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default Assignment
      btn_pressed_int <= '0';

      -- Combined Actions
      CASE current_state IS
         WHEN pressed => 
            btn_pressed_int <= '1';
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
   -----------------------------------------------------------------
   csm_wait_combo_proc: PROCESS (
      csm_timer,
      csm_to_s0
   )
   -----------------------------------------------------------------
   VARIABLE csm_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm_timer) = 0) THEN
         csm_temp_timeout := '1';
      ELSE
         csm_temp_timeout := '0';
      END IF;

      IF (csm_to_s0 = '1') THEN
         csm_next_timer <= "10010010011110111111111"; -- no cycles(4800000)-1=4799999
      ELSE
         IF (csm_temp_timeout = '1') THEN
            csm_next_timer <= (OTHERS=>'0');
         ELSE
            csm_next_timer <= unsigned(csm_timer) - '1';
         END IF;
      END IF;
      csm_timeout <= csm_temp_timeout;
   END PROCESS csm_wait_combo_proc;

END fsm;
