-- VHDL Entity alien_game_lib.c4_t1_bus_compare.symbol
--
-- Created:
--          by - USER.UNKNOWN (QUANG-PHAN)
--          at - 16:12:57 05/27/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t1_bus_compare IS
   PORT( 
      coord_1st : IN     std_logic_vector (7 DOWNTO 0);
      coord_2nd : IN     std_logic_vector (7 DOWNTO 0);
      match     : OUT    std_logic
   );

-- Declarations

END c4_t1_bus_compare ;

--
-- VHDL Architecture alien_game_lib.c4_t1_bus_compare.struct
--
-- Created:
--          by - USER.UNKNOWN (QUANG-PHAN)
--          at - 16:28:00 05/27/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c4_t1_bus_compare IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL match0 : std_logic;
   SIGNAL match1 : std_logic;
   SIGNAL match2 : std_logic;
   SIGNAL match3 : std_logic;
   SIGNAL match4 : std_logic;
   SIGNAL match5 : std_logic;
   SIGNAL match6 : std_logic;
   SIGNAL match7 : std_logic;


   -- Component Declarations
   COMPONENT c4_t1_bit_compare
   PORT (
      bit1  : IN     std_logic ;
      bit2  : IN     std_logic ;
      match : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c4_t1_bit_compare USE ENTITY alien_game_lib.c4_t1_bit_compare;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_8' of 'and'
   match <= match0 AND match1 AND match2 AND match3 AND match4 AND match5
            AND match6 AND match7;

   -- Instance port mappings.
   U_0 : c4_t1_bit_compare
      PORT MAP (
         bit1  => coord_1st(0),
         bit2  => coord_2nd(0),
         match => match0
      );
   U_1 : c4_t1_bit_compare
      PORT MAP (
         bit1  => coord_1st(1),
         bit2  => coord_2nd(1),
         match => match1
      );
   U_2 : c4_t1_bit_compare
      PORT MAP (
         bit1  => coord_1st(2),
         bit2  => coord_2nd(2),
         match => match2
      );
   U_3 : c4_t1_bit_compare
      PORT MAP (
         bit1  => coord_1st(3),
         bit2  => coord_2nd(3),
         match => match3
      );
   U_4 : c4_t1_bit_compare
      PORT MAP (
         bit1  => coord_1st(4),
         bit2  => coord_2nd(4),
         match => match4
      );
   U_5 : c4_t1_bit_compare
      PORT MAP (
         bit1  => coord_1st(5),
         bit2  => coord_2nd(5),
         match => match5
      );
   U_6 : c4_t1_bit_compare
      PORT MAP (
         bit1  => coord_1st(6),
         bit2  => coord_2nd(6),
         match => match6
      );
   U_7 : c4_t1_bit_compare
      PORT MAP (
         bit1  => coord_1st(7),
         bit2  => coord_2nd(7),
         match => match7
      );

END struct;
