-- VHDL Entity alien_game_lib.c4_t1_hit_detector.symbol
--
-- Created:
--          by - USER.UNKNOWN (QUANG-PHAN)
--          at - 21:56:26 05/27/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t1_hit_detector IS
   PORT( 
      alien_x_coord  : IN     std_logic_vector (7 DOWNTO 0);
      alien_y_coord  : IN     std_logic_vector (7 DOWNTO 0);
      bullet_x_coord : IN     std_logic_vector (7 DOWNTO 0);
      bullet_y_coord : IN     std_logic_vector (7 DOWNTO 0);
      clk            : IN     std_logic;
      rst_n          : IN     std_logic;
      hit            : OUT    std_logic
   );

-- Declarations

END c4_t1_hit_detector ;

--
-- VHDL Architecture alien_game_lib.c4_t1_hit_detector.struct
--
-- Created:
--          by - USER.UNKNOWN (QUANG-PHAN)
--          at - 21:56:26 05/27/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c4_t1_hit_detector IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL cur_match  : std_logic;
   SIGNAL dout       : std_logic;
   SIGNAL last_match : std_logic;
   SIGNAL match_x    : std_logic;
   SIGNAL match_y    : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'adff'
   SIGNAL mw_U_2reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_3' of 'adff'
   SIGNAL mw_U_3reg_cval : std_logic;

   -- Component Declarations
   COMPONENT c4_t1_bus_compare
   PORT (
      coord_1st : IN     std_logic_vector (7 DOWNTO 0);
      coord_2nd : IN     std_logic_vector (7 DOWNTO 0);
      match     : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c4_t1_bus_compare USE ENTITY alien_game_lib.c4_t1_bus_compare;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'adff'
   last_match <= mw_U_2reg_cval;
   u_2seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_2reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_2reg_cval <= cur_match;
      END IF;
   END PROCESS u_2seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'adff'
   hit <= mw_U_3reg_cval;
   u_3seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_3reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_3reg_cval <= dout;
      END IF;
   END PROCESS u_3seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'and'
   cur_match <= match_x AND match_y;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'and'
   dout <= cur_match AND NOT(last_match);

   -- Instance port mappings.
   U_0 : c4_t1_bus_compare
      PORT MAP (
         coord_1st => bullet_x_coord,
         coord_2nd => alien_x_coord,
         match     => match_x
      );
   U_1 : c4_t1_bus_compare
      PORT MAP (
         coord_1st => bullet_y_coord,
         coord_2nd => alien_y_coord,
         match     => match_y
      );

END struct;
