-- VHDL Entity alien_game_lib.c4_t1_bit_compare.symbol
--
-- Created:
--          by - USER.UNKNOWN (QUANG-PHAN)
--          at - 16:14:02 05/27/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t1_bit_compare IS
   PORT( 
      bit1  : IN     std_logic;
      bit2  : IN     std_logic;
      match : OUT    std_logic
   );

-- Declarations

END c4_t1_bit_compare ;

--
-- VHDL Architecture alien_game_lib.c4_t1_bit_compare.struct
--
-- Created:
--          by - USER.UNKNOWN (QUANG-PHAN)
--          at - 16:17:13 05/27/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c4_t1_bit_compare IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'and'
   dout <= NOT(bit1) AND NOT(bit2);

   -- ModuleWare code(v1.12) for instance 'U_1' of 'and'
   dout1 <= bit1 AND bit2;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'or'
   match <= dout OR dout1;

   -- Instance port mappings.

END struct;
