-- VHDL Entity alien_game_lib.c4_t1_hit_detector.symbol
--
-- Created:
--          by - USER.UNKNOWN (QUANG-PHAN)
--          at - 16:55:09 05/27/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c4_t1_hit_detector IS
   PORT( 
      alien_x_coord  : IN     std_logic_vector (7 DOWNTO 0);
      alien_y_coord  : IN     std_logic_vector (7 DOWNTO 0);
      bullet_x_coord : IN     std_logic_vector (7 DOWNTO 0);
      bullet_y_coord : IN     std_logic_vector (7 DOWNTO 0);
      clk            : IN     std_logic;
      rst_n          : IN     std_logic;
      hit            : OUT    std_logic
   );

-- Declarations

END c4_t1_hit_detector ;

--
-- VHDL Architecture alien_game_lib.c4_t1_hit_detector.struct
--
-- Created:
--          by - USER.UNKNOWN (QUANG-PHAN)
--          at - 16:55:09 05/27/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c4_t1_hit_detector IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL din1    : std_logic;
   SIGNAL dout    : std_logic;
   SIGNAL dout1   : std_logic;
   SIGNAL dout2   : std_logic;
   SIGNAL dout3   : std_logic;
   SIGNAL dout4   : std_logic;
   SIGNAL match_x : std_logic;
   SIGNAL match_y : std_logic;
   SIGNAL mux     : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL hit_internal : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'adff'
   SIGNAL mw_U_2reg_cval : std_logic;

   -- Component Declarations
   COMPONENT c4_t1_bus_compare
   PORT (
      coord_1st : IN     std_logic_vector (7 DOWNTO 0);
      coord_2nd : IN     std_logic_vector (7 DOWNTO 0);
      match     : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c4_t1_bus_compare USE ENTITY alien_game_lib.c4_t1_bus_compare;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'adff'
   hit_internal <= mw_U_2reg_cval;
   u_2seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_2reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_2reg_cval <= dout3;
      END IF;
   END PROCESS u_2seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'and'
   dout2 <= match_x AND match_y;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'constval'
   dout <= '1';

   -- ModuleWare code(v1.12) for instance 'U_7' of 'constval'
   dout4 <= '0';

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(hit_internal, dout, dout2)
   BEGIN
      CASE dout2 IS
      WHEN '0' => mux <= hit_internal;
      WHEN '1' => mux <= dout;
      WHEN OTHERS => mux <= 'X';
      END CASE;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'mux'
   u_6combo_proc: PROCESS(dout4, mux)
   BEGIN
      CASE mux IS
      WHEN '0' => dout3 <= dout4;
      WHEN '1' => dout3 <= mux;
      WHEN OTHERS => dout3 <= 'X';
      END CASE;
   END PROCESS u_6combo_proc;

   -- Instance port mappings.
   U_0 : c4_t1_bus_compare
      PORT MAP (
         coord_1st => bullet_x_coord,
         coord_2nd => alien_x_coord,
         match     => match_x
      );
   U_1 : c4_t1_bus_compare
      PORT MAP (
         coord_1st => bullet_y_coord,
         coord_2nd => alien_y_coord,
         match     => match_y
      );

   -- Implicit buffered output assignments
   hit <= hit_internal;

END struct;
